### ISSUE TITLE
Support for lists (ordered and unordered)

### ISSUE THREAD

**Issue by jean-luc** [inacho/bootstrap-markdown-editor#1]
Thanks for the great editor. 

Are there any plans to provide buttons / highlighting for lists `<ul>` and `<ol>`?

`* Item`
`* Item`
`* Item`

`1. Numbered item`
`2. Numbered item`
`3. Numbered item`

**Comment by inacho** [comment]
Hi,
I already added the buttons.
The highlighting depends of the theme used, you can change it easily passing the name of the theme as an option.
