### ISSUE TITLE
The project is discontinued, let's continue it?

### ISSUE THREAD

**Issue by mageddo** [inacho/bootstrap-markdown-editor#19]
ping @tricknotes  @okkez @kle-roy 

Guys I think the author @inacho will not continue this project, per months I've trying to talk with him on facebook, here, whatever, no success, no one "Hi" at least.

I have created a fork and redirect all this projects pull requests on there, someone wants to merge this pull requests? I will grant write permissions, all pull requests have no conflicts although  need to be tested on merge.

This project is really nice, I think that continue it will be a good thing.

The project links is https://github.com/mageddo/bootstrap-markdown-editor

**Comment by inacho** [comment]
Hi @mageddo,

Sorry for the late response. I was really busy until now and didn't have time to test and merge the pull requests.
From now I'm going to dedicate more attention to the project.

**Comment by tricknotes** [comment]
Welcome back! @inacho 
And thanks for your effort to continue this project @mageddo 

I think this is a very nice project :whale: 
I'm looking forward to proceeding with working :ship:

**Comment by mageddo** [comment]
Ok, let's going on
