### ISSUE TITLE
on focus on editor going to top of the page

### ISSUE THREAD

**Issue by mdrahiem** [inacho/bootstrap-markdown-editor#32]
Hello
Greetings

First of all thanks for the plugin. I have integrated with my app in comments section as an comment editor. Its working fine. But when I am focusing on the editor it is taking me to the top of the web page. Please let me know whats the solution for this.

Thanks

**Comment by jtl999** [comment]
same problem

**Comment by twinh** [comment]
Update ace editor to 1.2.6 can fix this problem

**Comment by sunic3** [comment]
i steel have this problem.
