### ISSUE TITLE
Markdown to html using markdown.js and to-markdown.js

### ISSUE THREAD

**Issue by PauBenetPrat** [inacho/bootstrap-markdown-editor#33]
Is it absolutely necessary to have an endpoint translating from markdown to html?

In [bootstrap-markdown.js](http://www.codingdrama.com/bootstrap-markdown/) they use bootstrap.js and to-bootstrap.js to automatically transform mardown to html. Is it possible to do the same with bootstrap-markdown-editor?

Thanks

**Comment by frostieDE** [comment]
You do not need to have a dedicated endpoint, you can also use JavaScript to transform markdown to html. We use [showdown ](https://github.com/showdownjs/showdown) (take a look at the `onPreview` option):

```javascript
+function($) {
    'use strict';

    $(document).ready(function() {
        var converter = new showdown.Converter();

        $('[data-editor=markdown]').each(function() {
            var $elem = $(this);
            var options = {
                /** your other options go here */
                preview: true,
                onPreview: function(content, callback) {
                    var html = converter.makeHtml(content);
                    callback(html);
                }
            };
    
            $elem.markdownEditor(options);
        });
    });
}(jQuery);
```

It is less magic but more flexible (compared to bootstrap-markdown.js) 😉

**Comment by PauBenetPrat** [comment]
Thanks! That looks perfect!
